#ifndef XFDBYTEKILLER_GLOBAL_H
#define XFDBYTEKILLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XFDBYTEKILLER_LIBRARY)
#  define XFDBYTEKILLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define XFDBYTEKILLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // XFDBYTEKILLER_GLOBAL_H
