#ifndef XFDPOWERPACKER_GLOBAL_H
#define XFDPOWERPACKER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XFDPOWERPACKER_LIBRARY)
#  define XFDPOWERPACKERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define XFDPOWERPACKERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // XFDPOWERPACKER_GLOBAL_H
