#ifndef XFDCRUNCHMANIA_GLOBAL_H
#define XFDCRUNCHMANIA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XFDCRUNCHMANIA_LIBRARY)
#  define XFDCRUNCHMANIASHARED_EXPORT Q_DECL_EXPORT
#else
#  define XFDCRUNCHMANIASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // XFDCRUNCHMANIA_GLOBAL_H
