#ifndef XFDIMPLODER_GLOBAL_H
#define XFDIMPLODER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(XFDIMPLODER_LIBRARY)
#  define XFDIMPLOLDERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define XFDIMPLOLDERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // XFDIMPLODER_GLOBAL_H
